POST http://localhost:3000/api/v1/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdGUxMjNAZW1haWwuY29tIiwiaWF0IjoxNjg3MzkxMTUwLCJleHAiOjE2ODczOTI5NTB9.GxzxVd9XO1hEVAfDqSdcwA2KVyCSDWyHjyDxlHkAu-I
Content-type: application/json


{
    "title": "projeto teste",
    "description": "projeto teste descrição",
    "user_id": [1,2]
}
###

GET http://localhost:3000/api/v1/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdGUxMjNAZW1haWwuY29tIiwiaWF0IjoxNjg3MzkxMTUwLCJleHAiOjE2ODczOTI5NTB9.GxzxVd9XO1hEVAfDqSdcwA2KVyCSDWyHjyDxlHkAu-I

###
GET http://localhost:3000/api/v1/project/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdGUxMjNAZW1haWwuY29tIiwiaWF0IjoxNjg3MzkxMTUwLCJleHAiOjE2ODczOTI5NTB9.GxzxVd9XO1hEVAfDqSdcwA2KVyCSDWyHjyDxlHkAu-I

###

PATCH http://localhost:3000/api/v1/project/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdGUxMjNAZW1haWwuY29tIiwiaWF0IjoxNjg3MzkxMTUwLCJleHAiOjE2ODczOTI5NTB9.GxzxVd9XO1hEVAfDqSdcwA2KVyCSDWyHjyDxlHkAu-I
Content-type: application/json

{
    "title": "teste patch",
    "description": "teste patch",
    "user_id": [2]
}
