POST http://localhost:3000/api/v1/user
Content-type: application/json

{
    "name": "usuario teste",
    "email": "teste123@email.com",
    "login": "loginTeste123",
    "password": "Teste123!"
}
###

GET http://localhost:3000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdGUxMjNAZW1haWwuY29tIiwiaWF0IjoxNjg3MzkxNTIzLCJleHAiOjE2ODczOTMzMjN9.pZfyp_oMaBrVy4LB0e_9OWBL5-29PHDSiijC5Wk0_qQ

###
GET http://localhost:3000/api/v1/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdGUxMjNAZW1haWwuY29tIiwiaWF0IjoxNjg3MzkxNTIzLCJleHAiOjE2ODczOTMzMjN9.pZfyp_oMaBrVy4LB0e_9OWBL5-29PHDSiijC5Wk0_qQ

###

PUT http://localhost:3000/api/v1/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGVzdGUxMjNAZW1haWwuY29tIiwiaWF0IjoxNjg3MzkxNTIzLCJleHAiOjE2ODczOTMzMjN9.pZfyp_oMaBrVy4LB0e_9OWBL5-29PHDSiijC5Wk0_qQ
Content-type: application/json

{
    "name": "teste123@email.com",
    "email": "teste123@email.com"
}

###
POST http://localhost:3000/api/auth/login
Content-type: application/json

{
    "login": "loginTeste123",
    "password": "$2b$10$OgnpZAQMJnlL.LLHTQJAkeE266t0WZruR4eQkhW4m9BDPmHm7wdKC"
}

###